spring.application.name=ll-meter-api

spring.datasource.url=jdbc:postgresql://localhost:5432/llm_meter
spring.datasource.username=llm_meter
spring.datasource.password=llm_meter

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false